- name: Set up SSH key
  run: |
    mkdir -p ~/.ssh
    echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/config
    chmod 600 ~/.ssh/config
    ssh-keyscan your-vm-ip >> ~/.ssh/known_hosts

- name: Execute deployment script via SSH
  run: ssh -i ~/.ssh/id_ed25519 edgar@35.203.84.129 'bash -s' < ./your-script.sh
